services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev --import-realm
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ${IMPORT_DIR_NAME}:/opt/keycloak/data/import
    depends_on:
      - database

  database:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: